version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: main.Dockerfile
    command: python /app/ml_service/ml_service_flask.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  db:
    image: postgres:13.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ml_service

volumes:
  postgres_data: