# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\"0\n\x10GetModelsRequest\x12\x1c\n\ttask_type\x18\x01 \x01(\x0e\x32\t.TaskType\"(\n\x11GetModelsResponse\x12\x13\n\x0bmodel_names\x18\x01 \x03(\t\"+\n\x15GetHyperParamsRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\".\n\x16GetHyperParamsResponse\x12\x14\n\x0chyper_params\x18\x01 \x03(\t\"z\n\x1bPredictOrCreateModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x14\n\x0chyper_params\x18\x02 \x01(\t\x12\x0f\n\x07retrain\x18\x03 \x01(\x08\x12\x10\n\x08\x63sv_path\x18\x04 \x01(\t\x12\x0e\n\x06target\x18\x05 \x01(\t\"?\n\x1cPredictOrCreateModelResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07predict\x18\x02 \x03(\x02\"(\n\x12RemoveModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"%\n\x13RemoveModelResponse\x12\x0e\n\x06status\x18\x01 \x01(\t*.\n\x08TaskType\x12\x12\n\x0e\x43LASSIFICATION\x10\x00\x12\x0e\n\nREGRESSION\x10\x01\x32\x90\x02\n\x08MlModule\x12\x32\n\tGetModels\x12\x11.GetModelsRequest\x1a\x12.GetModelsResponse\x12\x41\n\x0eGetHyperParams\x12\x16.GetHyperParamsRequest\x1a\x17.GetHyperParamsResponse\x12S\n\x14PredictOrCreateModel\x12\x1c.PredictOrCreateModelRequest\x1a\x1d.PredictOrCreateModelResponse\x12\x38\n\x0bRemoveModel\x12\x13.RemoveModelRequest\x1a\x14.RemoveModelResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKTYPE._serialized_start=475
  _TASKTYPE._serialized_end=521
  _GETMODELSREQUEST._serialized_start=20
  _GETMODELSREQUEST._serialized_end=68
  _GETMODELSRESPONSE._serialized_start=70
  _GETMODELSRESPONSE._serialized_end=110
  _GETHYPERPARAMSREQUEST._serialized_start=112
  _GETHYPERPARAMSREQUEST._serialized_end=155
  _GETHYPERPARAMSRESPONSE._serialized_start=157
  _GETHYPERPARAMSRESPONSE._serialized_end=203
  _PREDICTORCREATEMODELREQUEST._serialized_start=205
  _PREDICTORCREATEMODELREQUEST._serialized_end=327
  _PREDICTORCREATEMODELRESPONSE._serialized_start=329
  _PREDICTORCREATEMODELRESPONSE._serialized_end=392
  _REMOVEMODELREQUEST._serialized_start=394
  _REMOVEMODELREQUEST._serialized_end=434
  _REMOVEMODELRESPONSE._serialized_start=436
  _REMOVEMODELRESPONSE._serialized_end=473
  _MLMODULE._serialized_start=524
  _MLMODULE._serialized_end=796
# @@protoc_insertion_point(module_scope)
